### PR TITLE
Update jwt requirement from ~> 2.1 to ~> 2.2

### PR DESCRIPTION
**Pull request by leeh**
Update to most recent JWT library version.

### CODE REVIEW

**Comment by nbulaj** [comment]
Hi @leeh . What is the reason to increase version dependency? Is there any security issues with lower version?

**Comment by felixyz** [comment]
@nbulaj Needed to resolve this issue: https://github.com/nhosoya/omniauth-apple/issues/53

**Comment by nbulaj** [comment]
But any higher version of jwt could be used with current dependency without issues @felixyz , no? :thinking: The gem is used to encode the data, not decode. Sorry if I missing something

**Comment by felixyz** [comment]
@nbulaj Sorry haven't sorted out the details, but:

```
> bundle update jwt
Fetching gem metadata from https://rubygems.org/.........
Fetching gem metadata from https://rubygems.org/.
Resolving dependencies...
Bundler could not find compatible versions for gem "jwt":
  In Gemfile:
    jwt (~> 2.2.3)

    doorkeeper-jwt (~> 0.3.0) was resolved to 0.3.0, which depends on
      jwt (~> 2.1.0, >= 2.1.0)
```

It's the `~> 2.1.0` which conflicts.

**Comment by nbulaj** [comment]
Oh I see! Thanks
Let me do the fix

**Comment by nbulaj** [comment]
Done and released as 0.4.1
Thanks @leeh @felixyz :tada:

**Comment by felixyz** [comment]
:tada: Thanks!

**Pull request closed without merging**
